### ISSUE TITLE
com.freezingbear.network.mcpe.* missing

### ISSUE THREAD

**Issue by scr34m** [FreezingBear/FreezingBear#2]
Stuffs about subject content is missing so this plugin is unable to build.

**Comment by iNevet** [comment]
Plugin structure changed and the latest version will soon be published.

在 2015-08-30 16:09:59，"Győrvári Gábor" <notifications@github.com> 写道：


Stuffs about subject content is missing so this plugin is unable to build.

**Comment by scr34m** [comment]
i'm curious to see it, with the 0.12 patch almost the same content in the two platform
