### ISSUE TITLE
com.freezingbear.network.mcpe.FreezingPENetworkManager

### ISSUE THREAD

**Issue by Castar** [FreezingBear/FreezingBear#4]
You can update com.freezingbear.network.mcpe.FreezingPENetworkManager?

**Comment by haniokasai** [comment]
i dont know well,but it may be com.freezingbear.network.mcpe.FreezingPEPlayerConnection.

**Comment by haniokasai** [comment]
wasnt com.freezingbear.network.mcpe.FreezingPEPlayerConnection.....

**Comment by iNevet** [comment]
There will be a big network protocol change in the upcoming MCPE releases, so the development of FreezingBear stopped temporarily. We will continue our progress when the next version released, so keep watching (Click "Watch" in the project home page) FreezingBear and you will get the latest update when it's available.
Thank you! @Castar @haniokasai

**Comment by Castar** [comment]
@iNevet MCPE and MCPC is updated!
